from django.db import models

class SurveyResponse(models.Model):
    # Label1 = models.IntegerField(null=True)
    # Label2 = models.IntegerField(null=True)
    born_year = models.IntegerField(null=True)
    gender = models.IntegerField(null=True)
    hispanic = models.IntegerField(null=True)
    race = models.IntegerField(null=True)
    highest_level_school = models.IntegerField(null=True)
    marital_status = models.IntegerField(null=True)
    total_people_household = models.IntegerField(null=True)
    under_eighteen_people_household = models.IntegerField(null=True)
    covid_vaccine = models.IntegerField(null=True)
    covid_vaccine_all_doses = models.IntegerField(null=True)
    vaccine_opinion = models.IntegerField(null=True)
    covid_concern1 = models.IntegerField(null=True)
    covid_concern2 = models.IntegerField(null=True)
    covid_concern3 = models.IntegerField(null=True)
    covid_concern4 = models.IntegerField(null=True)
    covid_concern5 = models.IntegerField(null=True)
    covid_concern6 = models.IntegerField(null=True)
    covid_concern7 = models.IntegerField(null=True)
    covid_concern8 = models.IntegerField(null=True)
    covid_concern9 = models.IntegerField(null=True)
    covid_concern10 = models.IntegerField(null=True)
    covid_concern11 = models.IntegerField(null=True)
    covid_beliefs1 = models.IntegerField(null=True)
    covid_beliefs2 = models.IntegerField(null=True)
    covid_beliefs3 = models.IntegerField(null=True)
    covid_beliefs4 = models.IntegerField(null=True)
    covid_beliefs5 = models.IntegerField(null=True)
    covid_beliefs6 = models.IntegerField(null=True)
    had_covid_doctor = models.IntegerField(null=True)
    loss_income = models.IntegerField(null=True)
    loss_income_last_four_weeks = models.IntegerField(null=True)
    employement_last_seven_days = models.IntegerField(null=True)
    employed_by_who = models.IntegerField(null=True)
    reason_no_pay = models.IntegerField(null=True)
    nervousness = models.IntegerField(null=True)
    worry = models.IntegerField(null=True)
    no_pleasure = models.IntegerField(null=True)
    depression = models.IntegerField(null=True)
    insurance_union = models.IntegerField(null=True)
    insurance_private = models.IntegerField(null=True)
    insurance_medicare_disabilities = models.IntegerField(null=True)
    insurance_medicare_disability_low_income = models.IntegerField(null=True)
    insurance_military = models.IntegerField(null=True)
    insurance_va = models.IntegerField(null=True)
    insurance_indian = models.IntegerField(null=True)
    insurance_other = models.IntegerField(null=True)
    covid_delays_care = models.IntegerField(null=True)
    covid_prevents_care = models.IntegerField(null=True)
    prescription_mental = models.IntegerField(null=True)
    received_counseling = models.IntegerField(null=True)
    refused_conseling = models.IntegerField(null=True)